### ISSUE TITLE
update Script

### ISSUE THREAD

**Issue by BDadmehr0** [BDadmehr0/TNT-sms#1]
I have a problem in making the update itself. If someone can help me add this feature, I would be happy to volunteer

The code that should be reached is the exact main code in the main function of the third condition

**Comment by warlegend24** [comment]
what exactly do you want can you explain in detail plz
I am new to open source so didn't understand what is the feature and where it is to be updated?

**Comment by BDadmehr0** [comment]
I want to add a feature to the script that will download the latest version of the project and replace the previous one by selecting it

> what exactly do you want can you explain in detail plz I am new to open source so didn't understand what is the feature and where it is to be updated?
