### ISSUE TITLE
"name 'banner' is not defined" error

### ISSUE THREAD

**Issue by Moohsenam** [BDadmehr0/TNT-sms#5]
"Traceback (most recent call last):
  File "/root/TNT-sms/main.py", line 49, in <module>
    banner()
NameError: name 'banner' is not defined"

what's the solution?

**Comment by BDadmehr0** [comment]
I will check

**Comment by BDadmehr0** [comment]
> "Traceback (most recent call last): File "/root/TNT-sms/main.py", line 49, in banner() NameError: name 'banner' is not defined"
> 
> what's the solution?

It's done, try again and install the presets from the beginning
